
const fs = require('fs');

const esFile = 'src/assets/locales/es.json';
const enFile = 'src/assets/locales/en.json';

const esUpdates = {
    "ard.payment.selectCustomerAndAmount": "Por favor seleccione un cliente y verifique el monto.",
    "ard.payment.autoGeneratedNote": "Cobro generado automáticamente desde ARD. Documento: {docName}",
    "ard.payment.errorProcessing": "Error al procesar el cobro",
    "ard.payment.modalTitle": "Convertir a Cobro",
    "ard.payment.modalSubtitle": "Finalizar Ciclo ARD",
    "ard.payment.customerLabel": "Cliente",
    "ard.payment.selectCustomer": "Seleccione Cliente",
    "ard.payment.applyToInvoice": "Aplicar a Factura",
    "ard.payment.onAccount": "Pago a Cuenta (Sin Factura)",
    "ard.payment.amountReceived": "Monto Recibido",
    "ard.payment.date": "Fecha del Cobro",
    "ard.payment.method": "Método de Pago",
    "ard.payment.cancel": "Cancelar",
    "ard.payment.processing": "Procesando...",
    "ard.payment.confirm": "Confirmar Cobro ARD",
    "ard.payment.methods.cash": "Efectivo",
    "ard.payment.methods.check": "Cheque",
    "ard.payment.methods.transfer": "Transferencia",
    "ard.payment.methods.card": "Tarjeta",

    "ard.assign.modalTitle": "Asignar Cliente",
    "ard.assign.modalSubtitle": "Sincronización de Entidad ARD",
    "ard.assign.searchPlaceholder": "Escriba el nombre o ID del cliente...",
    "ard.assign.noMatches": "No se encontraron clientes coincidentes",
    "ard.assign.cancel": "Cancelar",
    "ard.assign.confirm": "Finalizar Asignación",

    "ard.sale.assignCustomerAlert": "Por favor, asigne un cliente para la venta.",
    "ard.sale.autoGeneratedDesc": "Venta generada desde ARD: {docName} ({vendor})",
    "ard.sale.autoGeneratedNote": "Conversión automática ARD ID: {docId}. Original: {docName}",
    "ard.sale.errorCreatingInvoice": "Error al crear la factura: {message}",
    "ard.sale.criticalError": "Error crítico durante la conversión",
    "ard.sale.modalTitle": "Convertir a Venta Real",
    "ard.sale.modalSubtitle": "Generación Automática de Factura",
    "ard.sale.ocrVerified": "Datos verificados por motor OCR - Listos para facturación",
    "ard.sale.targetCustomer": "Cliente Destino",
    "ard.sale.selectCustomerPlaceholder": "Seleccione el cliente para esta venta...",
    "ard.sale.invoiceNumber": "Nº de Factura",
    "ard.sale.saleDate": "Fecha Venta",
    "ard.sale.totalAmount": "Monto Total (Final)",
    "ard.sale.tax": "Impuestos (Tax)",
    "ard.sale.conceptDesc": "Concepto / Descripción",
    "ard.sale.cancel": "Cancelar",
    "ard.sale.processing": "Procesando Venta...",
    "ard.sale.complete": "Completar Conversión a Venta"
};

const enUpdates = {
    "ard.payment.selectCustomerAndAmount": "Please select a customer and verify the amount.",
    "ard.payment.autoGeneratedNote": "Payment generated automatically from ARD. Document: {docName}",
    "ard.payment.errorProcessing": "Error processing payment",
    "ard.payment.modalTitle": "Convert to Collection",
    "ard.payment.modalSubtitle": "Finalize ARD Cycle",
    "ard.payment.customerLabel": "Customer",
    "ard.payment.selectCustomer": "Select Customer",
    "ard.payment.applyToInvoice": "Apply to Invoice",
    "ard.payment.onAccount": "Payment on Account (No Invoice)",
    "ard.payment.amountReceived": "Amount Received",
    "ard.payment.date": "Collection Date",
    "ard.payment.method": "Payment Method",
    "ard.payment.cancel": "Cancel",
    "ard.payment.processing": "Processing...",
    "ard.payment.confirm": "Confirm ARD Collection",
    "ard.payment.methods.cash": "Cash",
    "ard.payment.methods.check": "Check",
    "ard.payment.methods.transfer": "Transfer",
    "ard.payment.methods.card": "Card",

    "ard.assign.modalTitle": "Assign Customer",
    "ard.assign.modalSubtitle": "ARD Entity Synchronization",
    "ard.assign.searchPlaceholder": "Type customer name or ID...",
    "ard.assign.noMatches": "No matching customers found",
    "ard.assign.cancel": "Cancel",
    "ard.assign.confirm": "Finalize Assignment",

    "ard.sale.assignCustomerAlert": "Please assign a customer for the sale.",
    "ard.sale.autoGeneratedDesc": "Sale generated from ARD: {docName} ({vendor})",
    "ard.sale.autoGeneratedNote": "Automatic conversion ARD ID: {docId}. Original: {docName}",
    "ard.sale.errorCreatingInvoice": "Error creating invoice: {message}",
    "ard.sale.criticalError": "Critical error during conversion",
    "ard.sale.modalTitle": "Convert to Real Sale",
    "ard.sale.modalSubtitle": "Automatic Invoice Generation",
    "ard.sale.ocrVerified": "Data verified by OCR engine - Ready for invoicing",
    "ard.sale.targetCustomer": "Target Customer",
    "ard.sale.selectCustomerPlaceholder": "Select customer for this sale...",
    "ard.sale.invoiceNumber": "Invoice #",
    "ard.sale.saleDate": "Sale Date",
    "ard.sale.totalAmount": "Total Amount (Final)",
    "ard.sale.tax": "Taxes",
    "ard.sale.conceptDesc": "Concept / Description",
    "ard.sale.cancel": "Cancel",
    "ard.sale.processing": "Processing Sale...",
    "ard.sale.complete": "Complete Conversion to Sale"
};

function update(file, updates) {
    try {
        let content = fs.readFileSync(file, 'utf8');
        if (content.charCodeAt(0) === 0xFEFF) content = content.slice(1);
        let json = JSON.parse(content);
        Object.assign(json, updates);
        fs.writeFileSync(file, JSON.stringify(json, null, 4));
        console.log(`✅ Updated ${file}`);
    } catch (e) {
        console.error(`❌ Error updating ${file}: ${e.message}`);
    }
}

update(esFile, esUpdates);
update(enFile, enUpdates);
