const fs = require('fs');
const accounts = [
    { code: '1000', name: 'ACTIVOS', type: 'asset', nb: 'debit', parent: null },
    { code: '1100', name: 'Activos Corrientes', type: 'asset', nb: 'debit', parent: '1000' },
    { code: '1110', name: 'Efectivo y Equivalentes', type: 'asset', nb: 'debit', parent: '1100' },
    { code: '1111', name: 'Caja Chica', type: 'asset', nb: 'debit', parent: '1110' },
    { code: '1112', name: 'Cuenta Corriente - Bank of America', type: 'asset', nb: 'debit', parent: '1110' },
    { code: '1113', name: 'Cuenta de Ahorros', type: 'asset', nb: 'debit', parent: '1110' },
    { code: '1114', name: 'Cuenta Payroll', type: 'asset', nb: 'debit', parent: '1110' },
    { code: '1120', name: 'Cuentas por Cobrar', type: 'asset', nb: 'debit', parent: '1100' },
    { code: '1121', name: 'Cuentas por Cobrar - Clientes', type: 'asset', nb: 'debit', parent: '1120' },
    { code: '1122', name: 'Provisión Cuentas Incobrables', type: 'asset', nb: 'credit', parent: '1120' },
    { code: '1123', name: 'Otras Cuentas por Cobrar', type: 'asset', nb: 'debit', parent: '1120' },
    { code: '1130', name: 'Inventario', type: 'asset', nb: 'debit', parent: '1100' },
    { code: '1131', name: 'Inventario - Productos Terminados', type: 'asset', nb: 'debit', parent: '1130' },
    { code: '1132', name: 'Inventario - Materias Primas', type: 'asset', nb: 'debit', parent: '1130' },
    { code: '1133', name: 'Inventario - Productos en Proceso', type: 'asset', nb: 'debit', parent: '1130' },
    { code: '1140', name: 'Gastos Pagados por Anticipado', type: 'asset', nb: 'debit', parent: '1100' },
    { code: '1141', name: 'Seguros Pagados por Anticipado', type: 'asset', nb: 'debit', parent: '1140' },
    { code: '1142', name: 'Alquileres Pagados por Anticipado', type: 'asset', nb: 'debit', parent: '1140' },
    { code: '1200', name: 'Activos No Corrientes', type: 'asset', nb: 'debit', parent: '1000' },
    { code: '1210', name: 'Propiedad, Planta y Equipo', type: 'asset', nb: 'debit', parent: '1200' },
    { code: '1211', name: 'Terrenos', type: 'asset', nb: 'debit', parent: '1210' },
    { code: '1212', name: 'Edificios', type: 'asset', nb: 'debit', parent: '1210' },
    { code: '1213', name: 'Deprec. Acumulada - Edificios', type: 'asset', nb: 'credit', parent: '1210' },
    { code: '1214', name: 'Maquinaria y Equipo', type: 'asset', nb: 'debit', parent: '1210' },
    { code: '1215', name: 'Deprec. Acumulada - Maquinaria', type: 'asset', nb: 'credit', parent: '1210' },
    { code: '1216', name: 'Vehículos', type: 'asset', nb: 'debit', parent: '1210' },
    { code: '1217', name: 'Deprec. Acumulada - Vehículos', type: 'asset', nb: 'credit', parent: '1210' },
    { code: '1218', name: 'Mobiliario y Equipo de Oficina', type: 'asset', nb: 'debit', parent: '1210' },
    { code: '1219', name: 'Deprec. Acumulada - Mobiliario', type: 'asset', nb: 'credit', parent: '1210' },
    { code: '1220', name: 'Activos Intangibles', type: 'asset', nb: 'debit', parent: '1200' },
    { code: '1221', name: 'Goodwill', type: 'asset', nb: 'debit', parent: '1220' },
    { code: '1222', name: 'Patentes y Marcas', type: 'asset', nb: 'debit', parent: '1220' },
    { code: '1223', name: 'Software', type: 'asset', nb: 'debit', parent: '1220' },
    { code: '1224', name: 'Amortiz. Acumulada - Intangibles', type: 'asset', nb: 'credit', parent: '1220' },
    { code: '2000', name: 'PASIVOS', type: 'liability', nb: 'credit', parent: null },
    { code: '2100', name: 'Pasivos Corrientes', type: 'liability', nb: 'credit', parent: '2000' },
    { code: '2110', name: 'Cuentas por Pagar', type: 'liability', nb: 'credit', parent: '2100' },
    { code: '2111', name: 'Cuentas por Pagar - Proveedores', type: 'liability', nb: 'credit', parent: '2110' },
    { code: '2112', name: 'Otras Cuentas por Pagar', type: 'liability', nb: 'credit', parent: '2110' },
    { code: '2120', name: 'Impuestos por Pagar', type: 'liability', nb: 'credit', parent: '2100' },
    { code: '2121', name: 'Sales Tax por Pagar (Florida)', type: 'liability', nb: 'credit', parent: '2120' },
    { code: '2122', name: 'Impuesto Federal por Pagar', type: 'liability', nb: 'credit', parent: '2120' },
    { code: '2123', name: 'Impuesto Estatal FL por Pagar', type: 'liability', nb: 'credit', parent: '2120' },
    { code: '2124', name: 'Payroll Taxes por Pagar', type: 'liability', nb: 'credit', parent: '2120' },
    { code: '2130', name: 'Nómina por Pagar', type: 'liability', nb: 'credit', parent: '2100' },
    { code: '2131', name: 'Sueldos y Salarios por Pagar', type: 'liability', nb: 'credit', parent: '2130' },
    { code: '2132', name: 'Retenciones por Pagar', type: 'liability', nb: 'credit', parent: '2130' },
    { code: '2140', name: 'Préstamos a Corto Plazo', type: 'liability', nb: 'credit', parent: '2100' },
    { code: '2141', name: 'Línea de Crédito', type: 'liability', nb: 'credit', parent: '2140' },
    { code: '2142', name: 'Porción Corriente Deuda LP', type: 'liability', nb: 'credit', parent: '2140' },
    { code: '2200', name: 'Pasivos No Corrientes', type: 'liability', nb: 'credit', parent: '2000' },
    { code: '2210', name: 'Préstamos a Largo Plazo', type: 'liability', nb: 'credit', parent: '2200' },
    { code: '2211', name: 'Hipotecas por Pagar', type: 'liability', nb: 'credit', parent: '2210' },
    { code: '2212', name: 'Préstamos Bancarios a Largo Plazo', type: 'liability', nb: 'credit', parent: '2210' },
    { code: '3000', name: 'PATRIMONIO', type: 'equity', nb: 'credit', parent: null },
    { code: '3100', name: 'Capital Social', type: 'equity', nb: 'credit', parent: '3000' },
    { code: '3110', name: 'Common Stock', type: 'equity', nb: 'credit', parent: '3100' },
    { code: '3120', name: 'Preferred Stock', type: 'equity', nb: 'credit', parent: '3100' },
    { code: '3200', name: 'Utilidades Retenidas', type: 'equity', nb: 'credit', parent: '3000' },
    { code: '3210', name: 'Utilidades del Ejercicio Actual', type: 'equity', nb: 'credit', parent: '3200' },
    { code: '3220', name: 'Utilidades de Ejercicios Anteriores', type: 'equity', nb: 'credit', parent: '3200' },
    { code: '3300', name: 'Dividendos', type: 'equity', nb: 'debit', parent: '3000' },
    { code: '3400', name: "Owner's Draw", type: 'equity', nb: 'debit', parent: '3000' },
    { code: '4000', name: 'INGRESOS', type: 'revenue', nb: 'credit', parent: null },
    { code: '4100', name: 'Ingresos Operacionales', type: 'revenue', nb: 'credit', parent: '4000' },
    { code: '4110', name: 'Ventas de Productos', type: 'revenue', nb: 'credit', parent: '4100' },
    { code: '4120', name: 'Ventas de Servicios', type: 'revenue', nb: 'credit', parent: '4100' },
    { code: '4130', name: 'Devoluciones y Descuentos s/Ventas', type: 'revenue', nb: 'debit', parent: '4100' },
    { code: '4200', name: 'Otros Ingresos', type: 'revenue', nb: 'credit', parent: '4000' },
    { code: '4210', name: 'Ingresos por Intereses', type: 'revenue', nb: 'credit', parent: '4200' },
    { code: '4220', name: 'Ganancia en Venta de Activos', type: 'revenue', nb: 'credit', parent: '4200' },
    { code: '4230', name: 'Ingresos Diversos', type: 'revenue', nb: 'credit', parent: '4200' },
    { code: '5000', name: 'COSTO DE VENTAS', type: 'expense', nb: 'debit', parent: null },
    { code: '5100', name: 'Costo de Productos Vendidos', type: 'expense', nb: 'debit', parent: '5000' },
    { code: '5110', name: 'Compras de Mercancía', type: 'expense', nb: 'debit', parent: '5100' },
    { code: '5120', name: 'Fletes y Acarreos', type: 'expense', nb: 'debit', parent: '5100' },
    { code: '5200', name: 'Costo de Servicios', type: 'expense', nb: 'debit', parent: '5000' },
    { code: '5210', name: 'Mano de Obra Directa', type: 'expense', nb: 'debit', parent: '5200' },
    { code: '5220', name: 'Materiales Directos', type: 'expense', nb: 'debit', parent: '5200' },
    { code: '6000', name: 'GASTOS OPERACIONALES', type: 'expense', nb: 'debit', parent: null },
    { code: '6100', name: 'Gastos de Ventas', type: 'expense', nb: 'debit', parent: '6000' },
    { code: '6110', name: 'Sueldos - Personal de Ventas', type: 'expense', nb: 'debit', parent: '6100' },
    { code: '6120', name: 'Comisiones de Ventas', type: 'expense', nb: 'debit', parent: '6100' },
    { code: '6130', name: 'Publicidad y Marketing', type: 'expense', nb: 'debit', parent: '6100' },
    { code: '6140', name: 'Gastos de Viaje - Ventas', type: 'expense', nb: 'debit', parent: '6100' },
    { code: '6200', name: 'Gastos Administrativos', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6210', name: 'Sueldos - Personal Administrativo', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6220', name: 'Alquiler de Oficina', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6230', name: 'Servicios Públicos', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6240', name: 'Teléfono e Internet', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6250', name: 'Suministros de Oficina', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6260', name: 'Seguros', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6270', name: 'Honorarios Profesionales', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6280', name: 'Depreciación y Amortización', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6290', name: 'Gastos de Mantenimiento', type: 'expense', nb: 'debit', parent: '6200' },
    { code: '6300', name: 'Gastos Financieros', type: 'expense', nb: 'debit', parent: '6000' },
    { code: '6310', name: 'Intereses sobre Préstamos', type: 'expense', nb: 'debit', parent: '6300' },
    { code: '6320', name: 'Comisiones Bancarias', type: 'expense', nb: 'debit', parent: '6300' },
    { code: '6330', name: 'Pérdida en Venta de Activos', type: 'expense', nb: 'debit', parent: '6300' },
    { code: '6400', name: 'Impuestos', type: 'expense', nb: 'debit', parent: '6000' },
    { code: '6410', name: 'Impuesto sobre la Renta', type: 'expense', nb: 'debit', parent: '6400' },
    { code: '6420', name: 'Impuestos Locales y Estatales', type: 'expense', nb: 'debit', parent: '6400' },
    { code: '6430', name: 'Property Tax', type: 'expense', nb: 'debit', parent: '6400' },
];

let res = '  static readonly DEFAULT_ACCOUNTS = [\n';
accounts.forEach(a => {
    let level;
    if (a.code.endsWith('00')) level = 1;
    else if (a.code.endsWith('0')) level = 2;
    else level = 3;
    const typeEnum = 'AccountType.' + a.type.toUpperCase();
    res += `    { code: '${a.code}', name: '${a.name}', type: ${typeEnum}, level: ${level}, normal_balance: '${a.nb}' as const },\n`;
});
res += '  ];\n';
fs.writeFileSync('output.txt', res);
