export const TRANSACTION_STATES = {
    IMPORTED: 'IMPORTED',
    VERIFIED: 'VERIFIED',
    PENDING: 'PENDING',
    HIGH_RISK_PERSONAL: 'HIGH_RISK_PERSONAL',
    PENDING_SUPERVISOR: 'PENDING_SUPERVISOR',
    DISPUTED: 'DISPUTED',
    RECLASSIFIED: 'RECLASSIFIED',
    RISK_DETECTED: 'RISK_DETECTED'
} as const;

export type TransactionState = typeof TRANSACTION_STATES[keyof typeof TRANSACTION_STATES];
