
import json
import sys

# Full map of translations inferred from key names
translations = {
    "1.0.0": "1.0.0",
    "2d": "2d",
    "Authorization": "Autorización",
    "CORRECT_JOURNAL_ENTRY": "CORREGIR_ASIENTO",
    "EXPIRING": "EXPIRANDO",
    "LOW_STOCK": "STOCK_BAJO",
    "MOVEMENTS": "MOVIMIENTOS",
    "T": "T",
    "TURNOVER": "ROTACIÓN",
    "USD": "USD",
    "VALUATION": "VALUACIÓN",
    "a": "a",
    "accounting": "Contabilidad",
    "accounting.accountType": "Tipo de Cuenta",
    "accounting.balance": "Saldo",
    "accounting.credit": "Crédito",
    "accounting.debit": "Débito",
    "accounting.netIncome": "Resultado Neto",
    "accounting.payroll": "Nómina",
    "accounting.reference": "Referencia",
    
    # Accounting Diagnosis
    "accountingDiagnosis.active": "Activo",
    "accountingDiagnosis.alphaOnline": "Alpha Online",
    "accountingDiagnosis.auditProtocolLabel": "Protocolo de Auditoría",
    "accountingDiagnosis.complete": "Completado",
    "accountingDiagnosis.criticalNetworkFailure": "Fallo Crítico de Red",
    "accountingDiagnosis.diagnosisAlert": "Alerta de Diagnóstico",
    "accountingDiagnosis.diagnosisNominal": "Diagnóstico Nominal",
    "accountingDiagnosis.endOfAuditTrace": "Fin de Rastro de Auditoría",
    "accountingDiagnosis.errorStatus": "Estado de Error",
    "accountingDiagnosis.high": "Alto",
    "accountingDiagnosis.historicalEntriesIndexed": "Asientos Históricos Indexados",
    "accountingDiagnosis.ledgerRegistry": "Registro de Mayor",
    "accountingDiagnosis.mainAccountsControl": "Control de Cuentas Principales",
    "accountingDiagnosis.masterAccountsInMemory": "Cuentas Maestras en Memoria",
    "accountingDiagnosis.multipleControlAccounts": "Múltiples Cuentas de Control",
    "accountingDiagnosis.networkIntegrity": "Integridad de Red",
    "accountingDiagnosis.optimal": "Óptimo",
    "accountingDiagnosis.planEntities": "Entidades del Plan",
    "accountingDiagnosis.reviewRequired": "Revisión Requerida",
    "accountingDiagnosis.runDeepDiagnosis": "Ejecutar Diagnóstico Profundo",
    "accountingDiagnosis.scanningSql": "Escaneando SQL",
    "accountingDiagnosis.sqlArchitecture": "Arquitectura SQL",
    "accountingDiagnosis.subtitle": "Diagnóstico del Sistema Contable",
    "accountingDiagnosis.synchronization": "Sincronización",
    "accountingDiagnosis.syncing": "Sincronizando",
    "accountingDiagnosis.systemTablesDetected": "Tablas del Sistema Detectadas",
    "accountingDiagnosis.title": "Diagnóstico Contable",
    "accountingDiagnosis.valid": "Válido",
    "accountingDiagnosis.verifyingIntegrity": "Verificando Integridad",
    
    "accrual": "Devengado",
    
    # Adjustments
    "adjustments.bestPractices": "Mejores Prácticas",
    "adjustments.checks.accruals": "Acumulaciones",
    "adjustments.checks.calcDepreciation": "Calcular Depreciación",
    "adjustments.checks.createEntry": "Crear Asiento",
    "adjustments.checks.depreciation": "Depreciación",
    "adjustments.checks.entriesRecorded": "Asientos Registrados",
    "adjustments.checks.goToInventory": "Ir a Inventario",
    "adjustments.checks.inventory": "Inventario",
    "adjustments.phaseDesc": "Descripción de Fase",
    "adjustments.phaseTitle": "Fase de Ajustes",
    
    "ai.detectIssues": "Detectar Problemas con IA",
    
    # ARD
    "ard.amountCol": "Columna Monto",
    "ard.analyzing": "Analizando",
    "ard.confirmDeleteAnalysis": "Confirmar Eliminación de Análisis",
    "ard.convertToDirectPayment": "Convertir a Pago Directo",
    "ard.convertToInvoice": "Convertir a Factura",
    "ard.converted": "Convertido",
    "ard.customerAssigned": "Cliente Asignado",
    "ard.dateCol": "Columna Fecha",
    "ard.documentCol": "Columna Documento",
    "ard.garHistory": "Historial GAR",
    "ard.noGarRecords": "Sin Registros GAR",
    "ard.numDocuments": "Núm. Documentos",
    "ard.processed": "Procesado",
    "ard.statusCol": "Columna Estado",
    "ard.viewAIAnalysis": "Ver Análisis IA",
    
    "arraybuffer": "búfer de arreglo",
    
    # Backup Panel
    "backupPanel.backupGeneratedAndSaved": "Copia de seguridad generada y guardada.",
    "backupPanel.chooseFileAndRestore": "Elegir archivo y restaurar",
    "backupPanel.chooseLocationAndSave": "Elegir ubicación y guardar",
    "backupPanel.criticalRestoreFailure": "Fallo Crítico de Restauración",
    "backupPanel.criticalSecurityWarning": "Advertencia de Seguridad Crítica",
    "backupPanel.errorGeneratingBackup": "Error generando copia de seguridad",
    "backupPanel.exportDesc": "Exportar descripción",
    "backupPanel.exportMasterCopy": "Exportar Copia Maestra",
    "backupPanel.operationError": "Error de Operación",
    "backupPanel.processing": "Procesando",
    "backupPanel.processorStatus": "Estado del Procesador",
    "backupPanel.restoreComplete": "Restauración Completa",
    "backupPanel.restoreCopy": "Restaurar Copia",
    "backupPanel.restoreDesc": "Descripción Restauración",
    "backupPanel.restoring": "Restaurando",
    "backupPanel.savingBackupAt": "Guardando copia en",
    "backupPanel.securityCenter": "Centro de Seguridad",
    "backupPanel.selectBackupLocation": "Seleccionar Ubicación",
    "backupPanel.startingEncryptionProtocol": "Iniciando Protocolo de Encriptación",
    "backupPanel.subtitle": "Gestión de Copias de Seguridad",
    "backupPanel.userCancelledOrError": "Cancelado por usuario o error",
    "backupPanel.verifyingSignature": "Verificando Firma",
    "backupPanel.waitingForFile": "Esperando archivo",
    
    # Bank Reconciliation
    "bankReconciliation.checks.balanceMatches": "Saldos Coinciden",
    "bankReconciliation.checks.noUnmatched": "Sin No Conciliados",
    "bankReconciliation.checks.openPanel": "Abrir Panel",
    "bankReconciliation.checks.reconciliationComplete": "Conciliación Completa",
    "bankReconciliation.phaseDesc": "Validación de transacciones bancarias contra registros contables.",
    "bankReconciliation.phaseTitle": "Fase de Conciliación Bancaria",
    "bankReconciliation.protocolTitle": "Protocolo de Conciliación",
    
    "blob": "blob",
    "canvas": "canvas",
    
    # Closure Checklist
    "closure.checklist.auditRecorded": "Auditoría Registrada",
    "closure.checklist.completedValidations": "Validaciones Completadas",
    "closure.checklist.errorActionRequired": "Error: Acción Requerida",
    "closure.checklist.errors": "Errores",
    "closure.checklist.passed": "Aprobado",
    "closure.checklist.pending": "Pendiente",
    "closure.checklist.readyToContinue": "Listo para Continuar",
    "closure.checklist.runValidations": "Ejecutar Validaciones",
    "closure.checklist.stepStatus": "Estado del Paso",
    "closure.checklist.technicalAudit": "Auditoría Técnica",
    "closure.checklist.title": "Lista de Verificación de Cierre",
    "closure.checklist.validating": "Validando",
    "closure.checklist.warnings": "Advertencias",
    "closure.checklist.warningsDetected": "Advertencias Detectadas",
    
    # Closure Report
    "closure.report.additionalNotes": "Notas Adicionales",
    "closure.report.auditTrail": "Rastro de Auditoría",
    "closure.report.closeDashboard": "Cerrar Dashboard",
    "closure.report.closedLocked": "Cerrado y Bloqueado",
    "closure.report.closingAudit": "Auditoría de Cierre",
    "closure.report.controls": "Controles",
    "closure.report.dateRange": "Rango de Fechas",
    "closure.report.difference": "Diferencia",
    "closure.report.doubleEntryVerification": "Verificación Partida Doble",
    "closure.report.downloadPdf": "Descargar PDF",
    "closure.report.entries": "Asientos",
    "closure.report.executedBy": "Ejecutado Por",
    "closure.report.kpis": "KPIs",
    "closure.report.monthly": "Mensual",
    "closure.report.netIncome": "Ingreso Neto",
    "closure.report.ok": "OK",
    "closure.report.periodDetails": "Detalles del Período",
    "closure.report.reportId": "ID Reporte",
    "closure.report.status": "Estado",
    "closure.report.technicalAdmin": "Admin Técnico",
    "closure.report.timestamp": "Marca de Tiempo",
    "closure.report.title": "Reporte de Cierre",
    "closure.report.totalCredits": "Total Créditos",
    "closure.report.totalDebits": "Total Débitos",
    "closure.report.totalExpenses": "Gastos Totales",
    "closure.report.totalRevenue": "Ingresos Totales",
    "closure.report.transVolume": "Volumen Trans.",
    "closure.report.type": "Tipo",
    "closure.report.wrn": "ADVERTENCIA",

    # Closure Steps
    "closure.steps.accountingAdjustments": "Ajustes Contables",
    "closure.steps.bankReconciliation": "Conciliación Bancaria",
    "closure.steps.confirmation": "Confirmación",
    "closure.steps.step": "Paso",
    "closure.steps.transactionValidation": "Validación de Transacciones",
    "closure.steps.trialBalance": "Balance de Comprobación",

    # Common
    "common.asset": "Activo",
    "common.credit": "Crédito",
    "common.debit": "Débito",
    "common.description": "Descripción",
    "common.equity": "Patrimonio",
    "common.expense": "Gasto",
    "common.export": "Exportar",
    "common.liability": "Pasivo",
    "common.of": "de",
    "common.options": "Opciones",
    "common.page": "Página",
    "common.payment": "Pago",
    "common.print": "Imprimir",
    "common.revenue": "Ingresos",
    "common.tools": "Herramientas",

    # Company Info
    "companyInfo.address": "Dirección",
    "companyInfo.baseCurrency": "Moneda Base",
    "companyInfo.city": "Ciudad",
    "companyInfo.cloudBackupEnabledDesc": "Copia en nube habilitada",
    "companyInfo.cloudVault": "Bóveda en Nube",
    "companyInfo.confirmUnlink": "Confirmar Desvinculación",
    "companyInfo.connectGDrive": "Conectar GDrive",
    "companyInfo.connectedToGDrive": "Conectado a GDrive",
    "companyInfo.contactEmail": "Email de Contacto",
    "companyInfo.gAuthError": "Error Autenticación Google",
    "companyInfo.legalName": "Razón Social",
    "companyInfo.linkCloudAccountDesc": "Vincular cuenta en la nube",
    "companyInfo.noCloudBackup": "Sin copia en nube",
    "companyInfo.saveChanges": "Guardar Cambios",
    "companyInfo.state": "Estado",
    "companyInfo.taxId": "Tax ID / EIN",
    "companyInfo.title": "Información de la Empresa",
    "companyInfo.unlink": "Desvincular",
    "companyInfo.uploadLogo": "Subir Logo",
    "companyInfo.zipCode": "Código Postal",

    # Confirmation Step
    "confirmationStep.auditPerformance": "Rendimiento de Auditoría",
    "confirmationStep.certify": "Certificar",
    "confirmationStep.certifyDesc": "Certifico la exactitud de estos datos de cierre.",
    "confirmationStep.confirmFinal": "Confirmación Final",
    "confirmationStep.consolidating": "Consolidando",
    "confirmationStep.end": "Fin",
    "confirmationStep.execution": "Ejecución",
    "confirmationStep.lockMsg": "Mensaje Bloqueo",
    "confirmationStep.metaInfo": "Meta Información",
    "confirmationStep.notesLabel": "Notas",
    "confirmationStep.notesPlaceholder": "Notas sobre el cierre...",
    "confirmationStep.periodName": "Nombre del Período",
    "confirmationStep.phaseDesc": "Fase Final de Cierre",
    "confirmationStep.phaseTitle": "Confirmación",
    "confirmationStep.securityLock": "Bloqueo de Seguridad",
    "confirmationStep.start": "Inicio",

    # Data Health
    "dataHealth.avgTime": "Tiempo Promedio",
    "dataHealth.checkHistory": "Historial de Chequeos",
    "dataHealth.checkNow": "Verificar Ahora",
    "dataHealth.checking": "Verificando",
    "dataHealth.consolidateDuplicates": "Consolidar Duplicados",
    "dataHealth.critical": "Crítico",
    "dataHealth.errorDetails": "Detalles del Error",
    "dataHealth.errors": "Errores",
    "dataHealth.fullReport": "Reporte Completo",
    "dataHealth.healthy": "Saludable",
    "dataHealth.lastCheck": "Último Chequeo",
    "dataHealth.manualActions": "Acciones Manuales",
    "dataHealth.neverChecked": "Nunca Verificado",
    "dataHealth.notChecked": "No Verificado",
    "dataHealth.recalculateTotals": "Recalcular Totales",
    "dataHealth.recommendations": "Recomendaciones",
    "dataHealth.repairReferences": "Reparar Referencias",
    "dataHealth.repairs": "Reparaciones",
    "dataHealth.subtitle": "Estado de Salud de Datos",
    "dataHealth.title": "Salud de Datos",
    "dataHealth.totalErrors": "Total Errores",
    "dataHealth.warning": "Advertencia",
    "dataHealth.warnings": "Advertencias",

    "database-initialized-success": "Base de datos inicializada exitosamente",
    "disposals": "Disposiciones",
    "error-boundary-reset": "Restablecer límites de error",

    # Fiscal Settings
    "fiscalSettings.quarterly": "Trimestral",

    # Florida Tax Report
    "floridaTaxReport.aboutDr15": "Sobre el Formulario DR-15",
    "floridaTaxReport.actions": "Acciones",
    "floridaTaxReport.allCounties": "Todos los Condados",
    "floridaTaxReport.back": "Atrás",
    "floridaTaxReport.calculateError": "Error de Cálculo",
    "floridaTaxReport.calculateSubtitle": "Subtítulo Cálculo",
    "floridaTaxReport.calculateTitle": "Cálculo de Impuestos",
    "floridaTaxReport.calculating": "Calculando",
    "floridaTaxReport.completedPeriodsOnly": "Solo períodos completados",
    "floridaTaxReport.countiesAvailable": "Condados Disponibles",
    "floridaTaxReport.countiesIncluded": "Condados Incluidos",
    "floridaTaxReport.county": "Condado",
    "floridaTaxReport.countyBreakdown": "Desglose por Condado",
    "floridaTaxReport.createFirstReport": "Crear Primer Reporte",
    "floridaTaxReport.dr15Breakdown": "Desglose DR-15",
    "floridaTaxReport.dr15DueDate": "Fecha de Vencimiento DR-15",
    "floridaTaxReport.dr15Frequency": "Frecuencia DR-15",
    "floridaTaxReport.dr15OfficialDesc": "Descripción Oficial DR-15",
    "floridaTaxReport.dueDate": "Fecha de Vencimiento",
    "floridaTaxReport.dueDateLabel": "Vencimiento",
    "floridaTaxReport.exemptSales": "Ventas Exentas",
    "floridaTaxReport.exportCsv": "Exportar CSV",
    "floridaTaxReport.exportError": "Error de Exportación",
    "floridaTaxReport.exportSuccess": "Exportación Exitosa",
    "floridaTaxReport.exporting": "Exportando",
    "floridaTaxReport.filed": "Presentado",
    "floridaTaxReport.fiscalPeriod": "Período Fiscal",
    "floridaTaxReport.floridaCounty": "Condado de Florida",
    "floridaTaxReport.generateReport": "Generar Reporte",
    "floridaTaxReport.late": "Tardío",
    "floridaTaxReport.legalNotice": "Aviso Legal",
    "floridaTaxReport.legalNoticeDesc": "El cumplimiento fiscal es responsabilidad del contribuyente.",
    "floridaTaxReport.loadCountiesError": "Error cargando condados",
    "floridaTaxReport.loadPeriodsError": "Error cargando períodos",
    "floridaTaxReport.loadReportsError": "Error cargando reportes",
    "floridaTaxReport.markAsFiled": "Marcar como Presentado",
    "floridaTaxReport.markFiledError": "Error al marcar como presentado",
    "floridaTaxReport.netTaxDue": "Impuesto Neto a Pagar",
    "floridaTaxReport.newReport": "Nuevo Reporte",
    "floridaTaxReport.noCalculatedReportError": "Error: Reporte no calculado",
    "floridaTaxReport.noReports": "Sin Reportes",
    "floridaTaxReport.noReportsDesc": "No hay reportes de impuestos disponibles.",
    "floridaTaxReport.noSalesForPeriod": "Sin ventas para el período",
    "floridaTaxReport.paid": "Pagado",
    "floridaTaxReport.pending": "Pendiente",
    "floridaTaxReport.period": "Período",
    "floridaTaxReport.rate": "Tasa",
    "floridaTaxReport.reportInfo": "Info Reporte",
    "floridaTaxReport.saveError": "Error al guardar",
    "floridaTaxReport.saveReport": "Guardar Reporte",
    "floridaTaxReport.saving": "Guardando",
    "floridaTaxReport.selectCounty": "Seleccionar Condado",
    "floridaTaxReport.selectCountyError": "Error selección condado",
    "floridaTaxReport.selectPeriod": "Seleccionar Período",
    "floridaTaxReport.selectPeriodAndCounty": "Seleccione período y condado",
    "floridaTaxReport.selectPeriodError": "Error selección período",
    "floridaTaxReport.status": "Estado",
    "floridaTaxReport.subtitle": "Reporte de Impuestos Florida DR-15",
    "floridaTaxReport.tax": "Impuesto",
    "floridaTaxReport.taxableSales": "Ventas Gravables",
    "floridaTaxReport.taxes": "Impuestos",
    "floridaTaxReport.taxesCollected": "Impuestos Recaudados",
    "floridaTaxReport.title": "Reporte Fiscal Florida",
    "floridaTaxReport.viewReport": "Ver Reporte",
    
    "force-app-refresh": "Forzar actualización de app",
    "hide-error-overlay": "Ocultar superposición de error",
    
    # Income Statement
    "incomeStatement.pdfAccount": "Cuenta PDF",
    "incomeStatement.pdfAmount": "Monto PDF",
    "incomeStatement.pdfCode": "Código PDF",
    "incomeStatement.pdfTotal": "Total PDF",
    
    "input": "Entrada",
    
    # Journal Entry
    "journalEntry.accountCodeHeader": "Código Cuenta",
    "journalEntry.accountPlaceholder": "Cuenta...",
    "journalEntry.addLine": "Agregar Línea",
    "journalEntry.auditGuideline": "Guía de Auditoría",
    "journalEntry.auditText": "Texto de Auditoría",
    "journalEntry.balanced": "Balanceado",
    "journalEntry.creditsHeader": "Créditos",
    "journalEntry.dateLabel": "Fecha",
    "journalEntry.debitsHeader": "Débitos",
    "journalEntry.deleteLineTitle": "Eliminar Línea",
    "journalEntry.descPlaceholder": "Descripción...",
    "journalEntry.descriptionLabel": "Descripción",
    "journalEntry.descriptionPlaceholder": "Describa la transacción",
    "journalEntry.lineDetailHeader": "Detalle de Línea",
    "journalEntry.manualEntrySubtitle": "Entrada Manual",
    "journalEntry.newFolio": "Nuevo Folio",
    "journalEntry.postEntry": "Publicar Asiento",
    "journalEntry.unbalanced": "Descuadrado",
    
    # Journal Entry Test
    "journalEntryTest.autoPurchases": "Compras Auto.",
    "journalEntryTest.autoSales": "Ventas Auto.",
    "journalEntryTest.billToLedgerProtocol": "Protocolo Fac. a Mayor",
    "journalEntryTest.cashEntryDesc": "Entrada Efectivo",
    "journalEntryTest.errorLoadingEntries": "Error cargando asientos",
    "journalEntryTest.generateTestEntry": "Generar Asiento Prueba",
    "journalEntryTest.invoiceToLedgerProtocol": "Protocolo Factura a Mayor",
    "journalEntryTest.latestLabRecords": "Últimos Registros Lab",
    "journalEntryTest.manualEntry": "Entrada Manual",
    "journalEntryTest.manualTestEntryDesc": "Asiento manual de prueba",
    "journalEntryTest.outOfPivot": "Fuera de Eje",
    "journalEntryTest.runTotalSuite": "Ejecutar Suite Completa",
    "journalEntryTest.serviceSaleDesc": "Venta Servicio",
    "journalEntryTest.subtitle": "Pruebas de Asientos Contables",
    "journalEntryTest.syncOk": "Sinc. OK",
    "journalEntryTest.testLogs": "Logs de Prueba",
    "journalEntryTest.title": "Prueba de Asientos",
    "journalEntryTest.waitingForExecution": "Esperando ejecución",
    
    "jspdf": "jspdf",
    
    "messages.loadingData": "Cargando datos...",
    "messages.noResults": "Sin resultados",
    "monthly": "Mensual",
    "navigate-to-dashboard": "Ir al Dashboard",
    "orderBy": "Ordenar Por",
    "pako": "pako",
    
    # Payroll Processor
    "payrollProcessor.alerts.closing": "Cierre",
    "payrollProcessor.alerts.consolidate": "Consolidar",
    "payrollProcessor.alerts.integrity": "Integridad",
    "payrollProcessor.alerts.integrityDesc": "Verificación de integridad de nómina.",
    "payrollProcessor.form.descriptor": "Descriptor",
    "payrollProcessor.form.execute": "Ejecutar",
    "payrollProcessor.form.payDate": "Fecha Pago",
    "payrollProcessor.form.reference": "Referencia",
    "payrollProcessor.form.sync": "Sincronizar",
    "payrollProcessor.form.totals.deductions": "Total Deducciones",
    "payrollProcessor.form.totals.gross": "Bruto Total",
    "payrollProcessor.form.totals.net": "Neto Total",
    "payrollProcessor.historyTitle": "Historial",
    "payrollProcessor.messages.error": "Error",
    "payrollProcessor.messages.selectEmployee": "Seleccionar Empleado",
    "payrollProcessor.messages.success": "Éxito",
    "payrollProcessor.newCycle": "Nuevo Ciclo",
    "payrollProcessor.preview.collab": "Colaborador",
    "payrollProcessor.preview.deductions": "Deducciones",
    "payrollProcessor.preview.gross": "Bruto",
    "payrollProcessor.preview.heuristic": "Heurística",
    "payrollProcessor.preview.net": "Neto",
    "payrollProcessor.preview.protocol": "Protocolo",
    "payrollProcessor.preview.title": "Vista Previa",
    "payrollProcessor.subtitle": "Procesador de Nómina",
    "payrollProcessor.table.dueDate": "Vencimiento",
    "payrollProcessor.table.file": "Archivo",
    "payrollProcessor.table.noData": "Sin datos",
    "payrollProcessor.table.period": "Período",
    "payrollProcessor.table.range": "Rango",
    "payrollProcessor.table.status": "Estado",
    "payrollProcessor.table.totalLiquidation": "Liquidación Total",
    "payrollProcessor.tabs.history": "Historial",
    "payrollProcessor.tabs.process": "Proceso",
    "payrollProcessor.tabs.settings": "Ajustes",
    "payrollProcessor.title": "Nómina",
    
    # Payroll Validation
    "payrollValidation.checks.approvalStatus": "Estado Aprobación",
    "payrollValidation.checks.entriesGenerated": "Asientos Generados",
    "payrollValidation.checks.ledgerSync": "Sinc. Mayor",
    "payrollValidation.checks.noPending": "Sin Pendientes",
    "payrollValidation.checks.processed": "Procesado",
    "payrollValidation.checks.reviewPayrolls": "Revisar Nóminas",
    "payrollValidation.checks.taxValidation": "Validación Impuestos",
    "payrollValidation.checks.taxesCalculated": "Impuestos Calculados",
    "payrollValidation.criticalAction": "Acción Crítica",
    "payrollValidation.guidelinesTitle": "Guías",
    "payrollValidation.messages.detected": "Detectado",
    "payrollValidation.messages.entriesLinked": "Asientos Vinculados",
    "payrollValidation.messages.entriesMissing": "Asientos Faltantes",
    "payrollValidation.messages.flowComplete": "Flujo Completo",
    "payrollValidation.messages.noTaxes": "Sin Impuestos",
    "payrollValidation.messages.noneInRange": "Ninguno en Rango",
    "payrollValidation.messages.ok": "OK",
    "payrollValidation.messages.pendingCount": "Cuenta Pendientes",
    "payrollValidation.messages.pnd": "PND",
    "payrollValidation.messages.taxAmount": "Monto Impuesto",
    "payrollValidation.pendingPayrollsWarning": "Advertencia Nóminas Pendientes",
    "payrollValidation.phaseDesc": "Fase de Validación",
    "payrollValidation.phaseTitle": "Validación Nómina",
    "payrollValidation.stats.executions": "Ejecuciones",
    "payrollValidation.stats.grossPay": "Pago Bruto",
    "payrollValidation.stats.net": "Neto",
    "payrollValidation.stats.taxLoad": "Carga Fiscal",
    "payrollValidation.stats.withholdings": "Retenciones",
    
    # Period Closing
    "periodClosing.accountingClosing": "Cierre Contable",
    "periodClosing.autoClosingDesc": "Desc. Cierre Auto",
    "periodClosing.autoClosingEntries": "Asientos Cierre Auto",
    "periodClosing.autoEntryGenerated": "Asiento Auto Generado",
    "periodClosing.back": "Atrás",
    "periodClosing.balanced": "Cuadrado",
    "periodClosing.cancel": "Cancelar",
    "periodClosing.closingEntrySuccess": "Asiento Cierre Exitoso",
    "periodClosing.closingError": "Error de Cierre",
    "periodClosing.codeAccount": "Cuenta Código",
    "periodClosing.confirm": "Confirmar",
    "periodClosing.continueAudit": "Continuar Auditoría",
    "periodClosing.continueToClosing": "Continuar al Cierre",
    "periodClosing.controlTotals": "Totales de Control",
    "periodClosing.criticalWarning": "Advertencia Crítica",
    "periodClosing.financialHealthReview": "Revisión Salud Financiera",
    "periodClosing.generateEntry": "Generar Asiento",
    "periodClosing.imbalance": "Descuadre",
    "periodClosing.integrityDesc": "Descripción Integridad",
    "periodClosing.nextAdjustments": "Siguientes Ajustes",
    "periodClosing.opIntegrityValidation": "Validación Integridad Op.",
    "periodClosing.periodCredits": "Créditos del Período",
    "periodClosing.periodDebits": "Débitos del Período",
    "periodClosing.periodLockedSuccess": "Período Bloqueado con Éxito",
    "periodClosing.periodTrialBalance": "Balance Comprobación Período",
    "periodClosing.poweredBy": "Impulsado por",
    "periodClosing.processing": "Procesando",
    "periodClosing.skipStep": "Saltar Paso",
    "periodClosing.steps.adjust": "Ajustar",
    "periodClosing.steps.audit": "Auditar",
    "periodClosing.steps.check": "Revisar",
    "periodClosing.steps.confirm": "Confirmar",
    "periodClosing.validations.auditIntact": "Auditoría Intacta",
    "periodClosing.validations.inventoryChecks": "Chequeos Inventario",
    "periodClosing.validations.ledgerBalanced": "Mayor Cuadrado",
    "periodClosing.validations.taxReconciled": "Impuestos Conciliados",
    "periodClosing.warningDesc": "Desc. Advertencia",
    "periodClosing.wizardTitle": "Asistente Cierre",
    
    # Period Closure (Another variant?)
    "periodClosure.auditActivated": "Auditoría Activada",
    "periodClosure.back": "Atrás",
    "periodClosure.closeError": "Error Cierre",
    "periodClosure.closing": "Cerrando",
    "periodClosure.continue": "Continuar",
    "periodClosure.errorUnknown": "Error Desconocido",
    "periodClosure.executeClosing": "Ejecutar Cierre",
    "periodClosure.milestone": "Hito",
    "periodClosure.periodNotFound": "Período No Encontrado",
    "periodClosure.processing": "Procesando",
    "periodClosure.steps.adjustments": "Ajustes",
    "periodClosure.steps.adjustmentsDesc": "Ajustes contables y depreciación.",
    "periodClosure.steps.bankReconciliation": "Conciliación Banc.",
    "periodClosure.steps.bankReconciliationDesc": "Verificar saldos bancarios.",
    "periodClosure.steps.confirmation": "Confirmación",
    "periodClosure.steps.confirmationDesc": "Cierre y bloqueo del período.",
    "periodClosure.steps.payroll": "Nómina",
    "periodClosure.steps.payrollDesc": "Procesamiento de pagos.",
    "periodClosure.steps.transactions": "Transacciones",
    "periodClosure.steps.transactionsDesc": "Revisión de movimientos.",
    "periodClosure.steps.trialBalance": "Balance Comp.",
    "periodClosure.steps.trialBalanceDesc": "Comprobación de saldos.",
    "periodClosure.systemError": "Error Sistema",
    "periodClosure.wizardCloseNote": "Nota Cierre Asistente",
    "periodClosure.wizardTitle": "Asistente de Cierre",
    
    "posted": "Publicado",
    "q": "T", # Quarter?
    "received": "Recibido",
    "register": "Registrar",
    
    # Reports Dashboard - Account Ledger
    "reportsDashboard.accountLedger.dateFrom": "Fecha Desde",
    "reportsDashboard.accountLedger.endingBalance": "Saldo Final",
    "reportsDashboard.accountLedger.ledgerTitle": "Título Mayor",
    "reportsDashboard.accountLedger.loadError": "Error Carga",
    "reportsDashboard.accountLedger.nature": "Naturaleza",
    "reportsDashboard.accountLedger.netMovements": "Movimientos Netos",
    "reportsDashboard.accountLedger.noMovements": "Sin Movimientos",
    "reportsDashboard.accountLedger.normalBalance": "Saldo Normal",
    "reportsDashboard.accountLedger.periodTotals": "Totales Período",
    "reportsDashboard.accountLedger.startingBalance": "Saldo Inicial",
    "reportsDashboard.accountLedger.subtitle": "Subtítulo Mayor",
    "reportsDashboard.accountLedger.title": "Libro Mayor",
    
    # Aging Report
    "reportsDashboard.agingReport.aging": "Antigüedad",
    "reportsDashboard.agingReport.current": "Corriente",
    "reportsDashboard.agingReport.customers": "Clientes",
    "reportsDashboard.agingReport.days": "Días",
    "reportsDashboard.agingReport.entity": "Entidad",
    "reportsDashboard.agingReport.entityDetail": "Detalle Entidad",
    "reportsDashboard.agingReport.loadError": "Error Carga",
    "reportsDashboard.agingReport.noPending": "Sin Pendientes",
    "reportsDashboard.agingReport.onTime": "A Tiempo",
    "reportsDashboard.agingReport.payable": "Por Pagar",
    "reportsDashboard.agingReport.payableBtn": "Btn Pagar",
    "reportsDashboard.agingReport.pendingAmount": "Monto Pendiente",
    "reportsDashboard.agingReport.receivable": "Por Cobrar",
    "reportsDashboard.agingReport.receivableBtn": "Btn Cobrar",
    "reportsDashboard.agingReport.riskAlert": "Alerta Riesgo",
    "reportsDashboard.agingReport.riskExcellent": "Riesgo Excelente",
    "reportsDashboard.agingReport.riskUrgent": "Riesgo Urgente",
    "reportsDashboard.agingReport.subtitle": "Reporte de Antigüedad de Saldos",
    "reportsDashboard.agingReport.suppliers": "Proveedores",
    "reportsDashboard.agingReport.title": "Antigüedad de Saldos",
    
    # Cash Flow
    "reportsDashboard.cashFlow.endingCash": "Efectivo Final",
    "reportsDashboard.cashFlow.liquidityInfo": "Info Liquidez",
    "reportsDashboard.cashFlow.loadError": "Error Carga",
    "reportsDashboard.cashFlow.netIncrease": "Aumento Neto",
    "reportsDashboard.cashFlow.operating": "Operativo",
    "reportsDashboard.cashFlow.startingCash": "Efectivo Inicial",
    "reportsDashboard.cashFlow.subtitle": "Flujos de Efectivo",
    "reportsDashboard.cashFlow.summaryTitle": "Resumen",
    "reportsDashboard.cashFlow.title": "Flujo de Caja",
    
    # Common Reports
    "reportsDashboard.common.actions": "Acciones",
    "reportsDashboard.common.excelError": "Error Excel",
    "reportsDashboard.common.excelSuccess": "Excel Éxito",
    "reportsDashboard.common.pdfError": "Error PDF",
    "reportsDashboard.common.pdfSuccess": "PDF Éxito",
    
    # DR15 Reports (Duplicate context but specific)
    "reportsDashboard.dr15.businessName": "Nombre Negocio",
    "reportsDashboard.dr15.certificateNumber": "Número Certificado",
    "reportsDashboard.dr15.certificationText": "Texto Certificación",
    "reportsDashboard.dr15.certificationTitle": "Certificación",
    "reportsDashboard.dr15.collectionPeriod": "Período Recaudación",
    "reportsDashboard.dr15.county": "Condado",
    "reportsDashboard.dr15.digitalSeal": "Sello Digital",
    "reportsDashboard.dr15.exemptSales": "Ventas Exentas",
    "reportsDashboard.dr15.generating": "Generando",
    "reportsDashboard.dr15.grossSales": "Ventas Brutas",
    "reportsDashboard.dr15.officialUseOnly": "Solo Uso Oficial",
    "reportsDashboard.dr15.pdfButton": "PDF",
    "reportsDashboard.dr15.subtitle": "Declaración de Impuestos",
    "reportsDashboard.dr15.summaryTitle": "Resumen",
    "reportsDashboard.dr15.surchargeBreakdown": "Desglose Recargos",
    "reportsDashboard.dr15.surchargeDue": "Recargo Debido",
    "reportsDashboard.dr15.taxableAmount": "Monto Gravable",
    "reportsDashboard.dr15.taxableSales": "Ventas Gravables",
    "reportsDashboard.dr15.title": "DR-15 Reporte",
    "reportsDashboard.dr15.totalTaxCollected": "Total Impuestos",
    "reportsDashboard.dr15.xmlButton": "XML",
    
    "schedule": "Programar",
    
    # Security Settings
    "securitySettings.aes256": "AES-256",
    "securitySettings.auditLogs": "Logs Auditoría",
    "securitySettings.auth2fa": "2FA",
    "securitySettings.title": "Seguridad",
    
    "sql.js": "sql.js",
    "sync-recovery-start": "Inicio Recuperación Sinc.",
    
    # System Logs
    "systemLogs.all": "Todos",
    "systemLogs.autoRefresh": "Auto-Refrescar",
    "systemLogs.clear": "Limpiar",
    "systemLogs.confirmClear": "Confirmar Limpieza",
    "systemLogs.criticals": "Críticos",
    "systemLogs.errorsByModule": "Errores por Módulo",
    "systemLogs.export": "Exportar",
    "systemLogs.last24Hours": "Últimas 24h",
    "systemLogs.level": "Nivel",
    "systemLogs.levels.all": "Todos",
    "systemLogs.levels.critical": "Crítico",
    "systemLogs.levels.debug": "Depuración",
    "systemLogs.levels.error": "Error",
    "systemLogs.levels.info": "Info",
    "systemLogs.levels.warn": "Advertencia",
    "systemLogs.limit": "Límite",
    "systemLogs.loadingRecords": "Cargando registros...",
    "systemLogs.module": "Módulo",
    "systemLogs.noRecordsMatch": "Sin coincidencias",
    "systemLogs.refresh": "Refrescar",
    "systemLogs.resolve": "Resolver",
    "systemLogs.resolved": "Resuelto",
    "systemLogs.status": "Estado",
    "systemLogs.statuses.all": "Todos",
    "systemLogs.statuses.resolved": "Resueltos",
    "systemLogs.statuses.unresolved": "No Resueltos",
    "systemLogs.subtitle": "Logs del Sistema",
    "systemLogs.systemRecords": "Registros de Sistema",
    "systemLogs.systemStats": "Estadísticas",
    "systemLogs.title": "Logs",
    "systemLogs.totalErrors": "Errores Totales",
    "systemLogs.unresolved": "No Resuelto",
    
    # Tax Rates
    "taxRates.actions": "Acciones",
    "taxRates.active": "Activo",
    "taxRates.importantNote": "Nota Importante",
    "taxRates.importantNoteDesc": "Las tasas se actualizan anualmente.",
    "taxRates.inactive": "Inactivo",
    "taxRates.status": "Estado",
    
    # Transaction Audit
    "transactionAudit.dateTime": "Fecha/Hora",
    "transactionAudit.emptyChain": "Cadena Vacía",
    "transactionAudit.entity": "Entidad",
    "transactionAudit.event": "Evento",
    "transactionAudit.hash": "Hash",
    "transactionAudit.id": "ID",
    "transactionAudit.loading": "Cargando...",
    "transactionAudit.subtitle": "Auditoría de Transacciones",
    "transactionAudit.title": "Auditoría",
    "transactionAudit.user": "Usuario",
    "transactionAudit.verified": "Verificado",
    "transactionAudit.verifyIntegrity": "Verificar Integridad",
    "transactionAudit.verifying": "Verificando",
    
    # Transaction Validation
    "transactionValidation.checks.billsRegistered": "Facturas Registradas",
    "transactionValidation.checks.entriesBalanced": "Asientos Cuadrados",
    "transactionValidation.checks.invoicesRegistered": "Ventas Registradas",
    "transactionValidation.checks.noPending": "Sin Pendientes",
    "transactionValidation.guidelinesTitle": "Guías",
    "transactionValidation.phaseDesc": "Validación de transacciones.",
    "transactionValidation.phaseTitle": "Validación Transacción",
    
    # Trial Balance
    "trialBalance.auditConsolidation": "Consolidación Auditoría",
    "trialBalance.auxHistory": "Historial Aux",
    "trialBalance.calibrated": "Calibrado",
    "trialBalance.closingBalance": "Saldo Final",
    "trialBalance.closingCredit": "Crédito Final",
    "trialBalance.closingDebit": "Débito Final",
    "trialBalance.codeHeader": "Código",
    "trialBalance.concept": "Concepto",
    "trialBalance.creditAction": "Acción Crédito",
    "trialBalance.creditConsumption": "Consumo Crédito",
    "trialBalance.creditFlow": "Flujo Crédito",
    "trialBalance.credits": "Créditos",
    "trialBalance.criticalImbalance": "Descuadre Crítico",
    "trialBalance.debitAction": "Acción Débito",
    "trialBalance.debitConsumption": "Consumo Débito",
    "trialBalance.debitFlow": "Flujo Débito",
    "trialBalance.debits": "Débitos",
    "trialBalance.descHeader": "Descripción",
    "trialBalance.diagnosis": "Diagnóstico",
    "trialBalance.diff": "Diferencia",
    "trialBalance.effectiveDate": "Fecha Efectiva",
    "trialBalance.entries": "Asientos",
    "trialBalance.error": "Error",
    "trialBalance.exportExcel": "Excel",
    "trialBalance.finishScan": "Finalizar Escaneo",
    "trialBalance.inconsistencyLog": "Log Inconsistencias",
    "trialBalance.injectDemo": "Inyectar Demo",
    "trialBalance.integrity": "Integridad",
    "trialBalance.integrityBook": "Libro Integridad",
    "trialBalance.natHeader": "Nat",
    "trialBalance.netDiagnosis": "Diagnóstico Neto",
    "trialBalance.noMovements": "Sin Movimientos",
    "trialBalance.openingBalance": "Saldo Inicial",
    "trialBalance.perfectSync": "Sincronía Perfecta",
    "trialBalance.periodLabel": "Período",
    "trialBalance.prevBalance": "Saldo Anterior",
    "trialBalance.protocol": "Protocolo",
    "trialBalance.reference": "Referencia",
    "trialBalance.registeredTrans": "Trans. Registradas",
    "trialBalance.repairConfirmation": "Confirmar Reparación",
    "trialBalance.repairStructure": "Estructura Reparación",
    "trialBalance.reportPDF": "Reporte PDF",
    "trialBalance.sessionID": "ID Sesión",
    "trialBalance.subtitle": "Balance de Comprobación",
    "trialBalance.syncDesc": "Descripción Sinc.",
    "trialBalance.syncing": "Sincronizando",
    "trialBalance.title": "Balance de Comprobación",
    "trialBalance.totalRecords": "Registros Totales",
    "trialBalance.verification": "Verificación",
    "trialBalance.viewLedger": "Ver Mayor",
    "trialBalance.zeroMovements": "Cero Movimientos",
    
    # Trial Balance Step
    "trialBalanceStep.checks.balanced": "Cuadrado",
    "trialBalanceStep.checks.classified": "Clasificado",
    "trialBalanceStep.checks.generated": "Generado",
    "trialBalanceStep.checks.noUnbalanced": "Sin Descuadres",
    "trialBalanceStep.controlPoints": "Puntos Control",
    "trialBalanceStep.download": "Descargar",
    "trialBalanceStep.mainAccount": "Cuenta Principal",
    "trialBalanceStep.netPosition": "Posición Neta",
    "trialBalanceStep.periodTotals": "Totales Período",
    "trialBalanceStep.phaseDesc": "Fase de Balance",
    "trialBalanceStep.phaseTitle": "Balance Comprobación",
    "trialBalanceStep.preview": "Vista Previa",
    "trialBalanceStep.successMsg": "Éxito",
    "trialBalanceStep.validating": "Validando",
    
    # User Role Manager
    "userRoleManager.assignedUser": "Usuario Asignado",
    "userRoleManager.assignedUsers": "Usuarios Asignados",
    "userRoleManager.newRole": "Nuevo Rol",
    "userRoleManager.roles.accountant": "Contador",
    "userRoleManager.roles.admin": "Admin",
    "userRoleManager.roles.sales": "Ventas",
    "userRoleManager.title": "Gestor Roles",
    
    # Verify Iron Core
    "verifyIronCore.activeTriggers": "Triggers Activos",
    "verifyIronCore.columnsDetected": "Columnas Detectadas",
    "verifyIronCore.countiesFound": "Condados Encontrados",
    "verifyIronCore.countingCounties": "Contando Condados",
    "verifyIronCore.criticalFailure": "Fallo Crítico",
    "verifyIronCore.emptyTableWarning": "Advertencia Tabla Vacía",
    "verifyIronCore.errorReadingCounties": "Error Leyendo Condados",
    "verifyIronCore.errorReadingScheme": "Error Leyendo Esquema",
    "verifyIronCore.errorReadingTriggers": "Error Leyendo Triggers",
    "verifyIronCore.fatalError": "Error Fatal",
    "verifyIronCore.immutabilitySuccess": "Inmutabilidad Exitosa",
    "verifyIronCore.populationInsufficient": "Población Insuficiente",
    "verifyIronCore.populationSuccessful": "Población Exitosa",
    "verifyIronCore.schemeCorrect": "Esquema Correcto",
    "verifyIronCore.schemeIncorrect": "Esquema Incorrecto",
    "verifyIronCore.starting": "Iniciando",
    "verifyIronCore.testingImmutability": "Probando Inmutabilidad",
    "verifyIronCore.title": "Verificación Iron Core",
    "verifyIronCore.triggersInstalled": "Triggers Instalados",
    "verifyIronCore.triggersMissing": "Triggers Faltantes",
    "verifyIronCore.unknownFailure": "Fallo Desconocido",
    "verifyIronCore.verifyingColumns": "Verificando Columnas",
    "verifyIronCore.verifyingTriggers": "Verificando Triggers",
    "warehouse": "Almacén"
}

file_path = "src/assets/locales/es.json"

try:
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    updated_count = 0

    def nested_update(obj, key_path, value):
        keys = key_path.split('.')
        current = obj
        for k in keys[:-1]:
            current = current.setdefault(k, {})
        current[keys[-1]] = value


    # Filter out keys that are prefixes of other keys to prevent overwriting dicts with strings
    # (e.g. 'accounting' string vs 'accounting.accountType' dict)
    sorted_keys = sorted(translations.keys())
    final_translations = {}
    
    for i, key in enumerate(sorted_keys):
        is_prefix = False
        # Check if this key is a prefix of any subsequent key
        # (Since sorted, only need to check forward)
        # But wait, 'accounting' comes before 'accounting.accountType' in sort? Yes.
        # But 'a' comes before 'accounting'? Yes.
        for other_key in sorted_keys[i+1:]:
            if other_key.startswith(key + "."):
                print(f"Skipping '{key}' because it conflicts with '{other_key}'")
                is_prefix = True
                break
        
        if not is_prefix:
            final_translations[key] = translations[key]

    for key, value in final_translations.items():
        # Update deep keys
        try:
            nested_update(data, key, value)
            updated_count += 1
        except Exception as e:
            print(f"Failed to update {key}: {e}")

        
    print(f"Successfully updated {updated_count} keys in {file_path}")

except Exception as e:
    print(f"Error: {e}")
